name: Test AD Kibana

on: 
  #schedule:
  #  - cron: '0 10 * * *'
  repository_dispatch:
    types: [test-build-deb-kibana]
  push:
    branches: 
      - weicongs-amazon-ad-kibana-it

jobs:

  
  Test-AD-Kibana-Plugin:
    runs-on: [ubuntu-16.04]
    strategy:
      matrix:
        java: [14]
    steps:
      - uses: actions/checkout@v1

      - name: Retrieve plugin tags 
        run:  echo ::set-env name=p_tag_ad::$(.github/scripts/plugin_tag.sh opendistro-for-elasticsearch/anomaly-detection-kibana-plugin)
    
      - name: Checkout Kibana
        uses: actions/checkout@v2
        with:
          repository: opendistro-for-elasticsearch/kibana-oss
          ref: 7.8.0
          token: ${{ secrets.READ_TOKEN }}
          path: kibana

      - name: check kibana plugin
        run: |
           pwd
           ls
           ls ../
           echo "checking kbn script"
           ls ../kibana/scripts/kbn.js
           
      - uses: actions/checkout@v1
        with:
          repository: opendistro-for-elasticsearch/anomaly-detection-kibana-plugin
          ref: ${{env.p_tag_ad}}
          path: kibana/plugins/anomaly-detection-kibana-plugin
      
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10.21.0
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install correct yarn version for Kibana
        run: |
          npm uninstall -g yarn
          echo "Installing yarn"
          npm i -g yarn@1.21.1
          ls ../
      
      - name: Bootstrap the plugin
        run: |
          pwd
          ls ../kibana/
          echo "checking kbn script"
          ls ../kibana/scripts/kbn.js
          cd ../kibana/plugins/anomaly-detection-kibana-plugin
          yarn kbn bootstrap
          
      - name: Start ES and Kibana
        run: |
          es_version=`./bin/version-info --es`
          echo $es_version
          cd elasticsearch/linux_distributions
          cd ../../..
          sleep 20
          sudo sysctl -w vm.max_map_count=262144

          sudo add-apt-repository -y ppa:openjdk-r/ppa
          sudo apt update -y
          sudo apt install -y openjdk-11-jdk
          sudo sudo apt install -y net-tools

          wget -qO - https://d3g5vo6xdbdb9a.cloudfront.net/GPG-KEY-opendistroforelasticsearch | sudo apt-key add -
          echo "deb https://d3g5vo6xdbdb9a.cloudfront.net/staging/apt stable main" | sudo tee -a /etc/apt/sources.list.d/opendistroforelasticsearch.list

          wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-$es_version-amd64.deb
          sudo dpkg -i elasticsearch-oss-$es_version-amd64.deb

          sudo apt-get -y update
          sudo apt install -y opendistroforelasticsearch
          
          sudo chmod 777 /etc/elasticsearch/elasticsearch.yml
          sudo chmod 777 /etc/elasticsearch/elasticsearch.yml
          sudo sed -i /^node.max_local_storage_nodes/d /etc/elasticsearch/elasticsearch.yml
          sudo /etc/init.d/elasticsearch start
          sleep 30
          
          curl -XGET https://127.0.0.1:9200 -u admin:admin --insecure
          sudo apt install opendistroforelasticsearch-kibana
          sudo systemctl start kibana.service
          sleep 120
          curl -v http://127.0.0.1:5601
          
      - name: run IT
        uses: cypress-io/github-action@v1
        with:
          working-directory: kibana/plugins/anomaly-detection-kibana-plugin
          command: yarn cy:run —config baseurl=http://localhost:5601
    
